spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/booktrack
    username: booktrack
    password: booktrack123

jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration-ms: 86400000

logging:
  level:
    booktrack: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
