spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/booktrack
    username: booktrack
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

  jpa:
    show-sql: false

jwt:
  secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metrics"

logging:
  level:
    root: INFO
    booktrack: INFO
